### ISSUE TITLE
Universal Issues

### ISSUE THREAD

**Issue by rambleraptor** [lloydpick/echelon#3]
Huge fan of the project! I noticed that Universal doesn't seem to be working properly. I'd love to contribute a PR, but I'm not entirely sure how you managed to get the secret keys. Mind enlightening me? I've seen the traffic through a MITM proxy, so I know the rest.

**Comment by lloydpick** [comment]
Hey,

When you say it's not working properly, are you getting blank data or?

**Comment by rambleraptor** [comment]
I'm getting the following error message:

JSON::ParserError: A JSON text must at least contain two octets!
    from /Users/Alex/.rvm/gems/ruby-2.0.0-p598/gems/json_pure-1.8.1/lib/json/common.rb:155:in `initialize'
    from /Users/Alex/.rvm/gems/ruby-2.0.0-p598/gems/json_pure-1.8.1/lib/json/common.rb:155:in`new'
    from /Users/Alex/.rvm/gems/ruby-2.0.0-p598/gems/json_pure-1.8.1/lib/json/common.rb:155:in `parse'
    from /Users/Alex/.rvm/gems/ruby-2.0.0-p598/gems/echelon-1.0.6/lib/echelon/parks/universal_studios_orlando.rb:45:in`initialize'
    from (irb):2:in `new'
    from (irb):2
    from /Users/Alex/.rvm/rubies/ruby-2.0.0-p598/bin/irb:12:in`<main>'

My best guess was that the JSON was returning empty because the page was returning blank with a 401 error. Maybe because the Secret key has changed? Or the server is dropping some requests? I've never debugged Ruby before (Python dev) so I'm not entirely sure how to prove this.

Additionally, I've noticed that you can actually get the wait times through their API without having to first authenticate. It sometimes takes a couple requests because their server seems to drop them though.

**Comment by lloydpick** [comment]
I'll have a look at this in the next few days, I'm a bit bogged down right now. Although I did just test this on my server and it seemed to run correctly. How are you calling the code?

**Comment by rambleraptor** [comment]
I'm calling it from irb using the following two statements:

require 'echelon'
uo = Echelon::UniversalStudiosOrlando.new

**Comment by rambleraptor** [comment]
I just ran it through a debugger. The HTTP response for the authorization token is returning: #Net::HTTPUnauthorized:0x007fa4e296cec0nil with a nil response body.

**Comment by lloydpick** [comment]
Managed to figure it out, my server where I was testing has it's timezone set to UTC, so it never appeared there, and never appeared on my laptop until the UK entered DST (last night). Basically, the UO server wants the time in UTC, but the string it's sent in must say that it's GMT... even though it isn't. But should be fixed now, I'm just going to create a new release in a little bit tonight.
