### ISSUE TITLE
The API doesn't seem to work for Disneyland CA 

### ISSUE THREAD

**Issue by Todd-Werelius** [lloydpick/echelon#4]
I read that Disneyland (CA) and California Adventures shut down their API, this seems to be confirmed when I try those parks using your gem.  Is this correct?

**Comment by rambleraptor** [comment]
Disneyland and DCA now use the same API as the DisneyWorld parks. I can make the changes to make those inherit from DisneyWorld if you would like.

**Comment by Todd-Werelius** [comment]
Yes very much would like, thanks

**Comment by rambleraptor** [comment]
See PR #5 for a tentative fix.

**Comment by Todd-Werelius** [comment]
Checked, seems to work fine!

**Comment by Todd-Werelius** [comment]
Thanks!
